### ISSUE TITLE
Code not longer avaible

### ISSUE THREAD

**Issue by HeinzAlberto** [ultramango/gear360reveng#10]
Hey there!
I noticed that the source code for the Gear 360 is not longer avaible for download on the Samsung website.

Since I want to build an long-exposure mode, it would be really helpful to have some of the source code.
Can someone privide me the "bundle" directly?

**Thank you all in advance!**

**Comment by ultramango** [comment]
Hi,

Let me check if I have anything.

Be aware that the application itself is not open-source - one that controls the camera.

Lukasz.

**Comment by ultramango** [comment]
Sorry, I don't have it in my archives.

I guess you could send an inquiry to Samsung to request the source code: https://opensource.samsung.com/requestInquiry

Lukasz.

**Comment by HeinzAlberto** [comment]
Too sad! - Thank you anyway a lot! ^_^

~ Heinz

**Comment by HeinzAlberto** [comment]
Kind of embarrassing...
A minute after sending a requst, I found the files on their website ^_^'
Looks like they just have moved them...

So here's a link were you find the source code now:

https://opensource.samsung.com/uploadSearch?searchValue=c200
