### ISSUE TITLE
shutter speed hack

### ISSUE THREAD

**Issue by utack** [ultramango/gear360reveng#5]
Hi @ultramango 
did you come accross anything in the camera app, that suggests we could allow longer shutter times?
That would be an excellent hack to have with iso400+tripod
Thanks

**Comment by ultramango** [comment]
Hi!

Unfortunately no. My research stopped at dissecting the firmware.

At low level (sensor) I think it's possible and I suspect that the software should also have such an option (or maybe it is statically set).

L.
